# PySNMP SMI module. Autogenerated from smidump -f python AXON-MIB
# by libsmi2pysnmp-0.1.3 at Wed Sep  5 16:20:15 2018,
# Python version sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)

# Imports

( MibScalar, MibTable, MibTableRow, MibTableColumn,) = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn")
( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")

# Objects
internet = MibIdentifier((1, 3, 6, 1)) 
enterprises = MibIdentifier((1, 3, 6, 1, 4, 1)) 
digiEnterprise = MibIdentifier((1, 3, 6, 1, 4, 1, 332))
digiProducts = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11))
digiTerminalServers = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 5))
digiPortServers = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 5, 3))
digiPortServerTS = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 5, 3, 3))
general = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 5, 3, 20))
digiSnmpOidModel = MibScalar((1, 3, 6, 1, 4, 1, 332, 11, 5, 3, 20, 11), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: digiSnmpOidModel.setDescription("")
digiSnmpOidType = MibScalar((1, 3, 6, 1, 4, 1, 332, 11, 5, 3, 20, 12), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: digiSnmpOidType.setDescription("Axon Model")
digiConnect = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 6))
digiDeviceInfo = MibIdentifier((1, 3, 6, 1, 4, 1, 332, 11, 6, 1))
digiEsSnmpOidModel = MibScalar((1, 3, 6, 1, 4, 1, 332, 11, 6, 1, 1), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: digiEsSnmpOidModel.setDescription("Terminal Server for Axon model")

# Augmentions

# Exports

# Objects
mibBuilder.exportSymbols("AXON-MIB", digiEnterprise=digiEnterprise, digiProducts=digiProducts, digiTerminalServers=digiTerminalServers, digiPortServers=digiPortServers, digiPortServerTS=digiPortServerTS, general=general, digiSnmpOidModel=digiSnmpOidModel, digiSnmpOidType=digiSnmpOidType, digiConnect=digiConnect, digiDeviceInfo=digiDeviceInfo, digiEsSnmpOidModel=digiEsSnmpOidModel)

